export const clothes = [
    {
        id: 1,
        spain: "la camiseta",
        polish: "koszulka",
        picture: "./img/clothes/tshirt.jpg",
        alternate: "./img/clothes/trousers.jpg",
    },
    {
        id: 2,
        spain: "el pantalones",
        polish: "spodnie",
        picture: "./img/clothes/trousers.jpg",
        alternate: "./img/clothes/jumper.jpg"
    },
    {
        id: 3,
        spain: "el vestido",
        polish: "sukienka",
        picture: "./img/clothes/dress.jpg",
        alternate: "./img/clothes/cup.jpg",
    },
    {
        id: 4,
        spain: "el jersey",
        polish: "sweter",
        picture: "./img/clothes/jumper.jpg",
        alternate: "./img/clothes/shoes.jpg",
    },
    {
        id: 5,
        spain: "la chaqueta",
        polish: "kurtka",
        picture: "./img/clothes/jacket.jpg",
        alternate: "./img/clothes/tshirt.jpg",
    },
    {
        id: 6,
        spain: "el gorro",
        polish: "czapka",
        picture: "./img/clothes/cup.jpg",
        alternate: "./img/clothes/pants.jpg",
    },
    {
        id: 7,
        spain: "la bufanda",
        polish: "szalik",
        picture: "./img/clothes/scarf.jpg",
        alternate: "./img/clothes/dress.jpg",
    },
    {
        id: 8,
        spain: "la bragas",
        polish: "majtki",
        picture: "./img/clothes/pants.jpg",
        alternate: "./img/clothes/jacket.jpg",
    },
    {
        id: 9,
        spain: "los zapatos",
        polish: "buty",
        picture: "./img/clothes/shoes.jpg",
        alternate: "./img/clothes/scarf.jpg",
    },
]